WebMotors.App/Models/Domain/Anuncio.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMotors.App.Models.Domain
{
	public class Anuncio
	{
        [JsonProperty(PropertyName = "ID")]
        public int ID { get; set; }

        [JsonProperty(PropertyName = "Marca")]
        public string Marca { get; set; }

        [JsonProperty(PropertyName = "Modelo")]
        public string Modelo { get; set; }

        [JsonProperty(PropertyName = "Versao")]
        public string Versao { get; set; }

        [JsonProperty(PropertyName = "Ano")]
        public int Ano { get; set; }

        [JsonProperty(PropertyName = "Quilometragem")]
        public int Quilometragem { get; set; }

        [JsonProperty(PropertyName = "Observacao")]
        public string Observacao { get; set; }
    }
}

WebMotors.App/Models/Domain/Make.cs
namespace WebMotors.App.Models.Domain
{
	public class Make
	{
		public int ID { get; set; }
		public string Name { get; set; }
	}
}

WebMotors.App/Models/Domain/Model.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMotors.App.Models.Domain
{
	public class Model
	{
		public int ID { get; set; }
		public int MakeID { get; set; }
		public string Name { get; set; }
	}
}

WebMotors.App/Models/Domain/Version.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMotors.App.Models.Domain
{
	public class Version
	{
		public int ID { get; set; }
		public int ModelID { get; set; }
		public string Name { get; set; }
	}
}

WebMotors.App/Models/ErrorViewModel.cs
using System;

namespace WebMotors.App.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

WebMotors.App/Models/ViewModels/AnuncioViewModel.cs
using WebMotors.App.Models.Domain;
using System.Collections.Generic;

namespace WebMotors.App.Models.ViewModels
{
	public class AnuncioViewModel
	{
		public Anuncio Anuncio { get; set; }
		public IList<Make> Makes { get; set; }
		public IList<Model> Model { get; set; }
		public IList<Version> Version { get; set; }
	}
}

WebMotors.App/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMotors.App.Models;
using WebMotors.App.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using WebMotors.App.Services;
using WebMotors.App.Models.Domain;

namespace WebMotors.App.Controllers
{
    public class AnunciosController : Controller
    {
        private readonly IAnuncioService _anuncioService;
		private readonly IMakeService _makeService;
		private readonly IModelService _modelService;
		private readonly IVersionService _versionService;

		public AnunciosController(IAnuncioService anuncioService,
								IMakeService makeService,
								IModelService modelService,
								IVersionService versionService)
		{
			_anuncioService = anuncioService;
			_makeService = makeService;
			_modelService = modelService;
			_versionService = versionService;
		}

		public async Task<IActionResult> Index()
        {          
            var anuncios = await _anuncioService.GetAsync();
            return View(anuncios);          
        }

		public async Task<IActionResult> Details(int id)
		{			
			var anuncios = await _anuncioService.GetByIdAsync(id);

			if (anuncios == null)
				return NotFound();
			else
				return View(anuncios);
		}

		public async Task<IActionResult> Create()
		{
			AnuncioViewModel model = new AnuncioViewModel() { Anuncio = new Anuncio(), 
															  Makes = await _makeService.GetAsync() };
			return View(model);
		}
		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Marca,Modelo,Versao,Ano,Quilometragem,Observacao")] Anuncio anuncio)
		{
			if (ModelState.IsValid)
			{
				var ret = await _anuncioService.CreateAsync(anuncio);
				
				return RedirectToAction(nameof(Index));
			}
			return View(anuncio);
		}

		public async Task<IActionResult> Edit(int id)
		{
			var anuncio = await _anuncioService.GetByIdAsync(id);
		
			if (anuncio == null)
			{
				return NotFound();
			}
			var viewModel = new AnuncioViewModel() {
				Anuncio = anuncio,
				Makes = await _makeService.GetAsync()
			};
			return View(viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit( [Bind("ID,Marca,Modelo,Versao,Ano,Quilometragem,Observacao")] Anuncio anuncio)
		{
			await _anuncioService.UpdateAsync(anuncio);

			return RedirectToAction(nameof(Index));
       
		}
		
		public async Task<IActionResult> Delete(int id)
		{
			var anuncio = await _anuncioService.GetByIdAsync(id);

			if (anuncio == null)
			{
				return NotFound();
			}
			
			return View(anuncio);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await _anuncioService.RemoveAsync(id);
			return RedirectToAction(nameof(Index));
		}

		public async Task<JsonResult> GetModel(int id)
		{
			return Json(await _modelService.GetAsync(id));
		}

		public async Task<JsonResult> GetVersion(int id)
		{
			return Json(await _versionService.GetAsync(id));
		}
	}
}

WebMotors.App/Views/Anuncios/Create.cshtml
@model WebMotors.App.Models.ViewModels.AnuncioViewModel
@{
	ViewData["Title"] = "Anuncio";
}

	<h1>Cadastro de Anuncio</h1>
<script src="~/lib/jquery/dist/jquery.js"></script>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Anuncio.Marca" class="control-label"></label>
				<select id="ddlMarca" asp-for="Anuncio.Marca" required asp-items="@(new SelectList(Model.Makes,"ID","Name"))" class="form-control">
					<option selected="selected" value="">Selecione</option>
				</select>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Modelo" class="control-label"></label>
				<select id="ddlModelo" asp-for="Anuncio.Modelo" required asp-items="@(new SelectList(string.Empty ,"ID","Name"))" class="form-control">
					<option selected="selected" value="">Selecione</option>
				</select>
				<span asp-validation-for="Anuncio.Modelo" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Versao" class="control-label"></label>
				<select id="ddlVersion" asp-for="Anuncio.Versao" required asp-items="@(new SelectList(string.Empty,"ID","Name"))" class="form-control">
					<option selected="selected" value="">Selecione</option>
				</select>
				<span asp-validation-for="Anuncio.Versao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Ano" class="control-label"></label>
				<input asp-for="Anuncio.Ano" required class="form-control" />
				<span asp-validation-for="Anuncio.Ano" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Quilometragem" class="control-label"></label>
				<input asp-for="Anuncio.Quilometragem" required class="form-control" />
				<span asp-validation-for="Anuncio.Quilometragem" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Observacao" class="control-label"></label>
				<textarea asp-for="Anuncio.Observacao" rows="5" cols="40" maxlength="200" required class="form-control"></textarea>
				<span asp-validation-for="Anuncio.Observacao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Salvar" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index" class="btn btn-default">Voltar</a>
</div>
<script>
	$(function () {
		$("#ddlMarca").change(function () {
			$.getJSON("/Anuncios/GetModel", { id: $("#ddlMarca").val() }, function (data) {
				var row = "";
				$("#ddlModelo").empty();
				row += "<option value=''>Selecione</option>";
				$.each(data, function (i, model) {					
					row += "<option value=" + model.id + ">" + model.name + "</option>";
				});
				$("#ddlModelo").html(row);
				$("#ddlVersion").empty();
				$("#ddlVersion").html("<option value=''>Selecione</option>");
			})
		})
		$("#ddlModelo").change(function () {
			$.getJSON("/Anuncios/GetVersion", { id: $("#ddlModelo").val() }, function (data) {
				var row = "";
				$("#ddlVersion").empty();
				row += "<option value=''>Selecione</option>";
				$.each(data, function (i, version) {
					row += "<option value=" + version.id + ">" + version.name + "</option>";
				});
				$("#ddlVersion").html(row);
			})
		})
	})
</script>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMotors.App/Views/Anuncios/Delete.cshtml
@model WebMotors.App.Models.Domain.Anuncio
@{
	ViewData["Title"] = "Anuncio";
}

<h1>Apagar Anuncio</h1>
<br />
<h3>Esta certo que deseja apagar este anuncio?</h3>
<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ID)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ID)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Marca)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Marca)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Modelo)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Modelo)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Versao)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Versao)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Quilometragem)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Quilometragem)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Ano)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Ano)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Observacao)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Observacao)
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="ID" />
		<input type="submit" value="Delete" class="btn btn-danger" /> |
		<a asp-action="Index" class="btn btn-default">Voltar</a>
	</form>
</div>

WebMotors.App/Views/Anuncios/Details.cshtml
@model WebMotors.App.Models.Domain.Anuncio
@{
	ViewData["Title"] = "Anuncio";
}
<div>
	<h4>Detalhe Anuncio</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ID)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ID)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Marca)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Marca)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Modelo)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Modelo)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Versao)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Versao)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Quilometragem)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Quilometragem)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Ano)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Ano)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Observacao)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Observacao)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-primary">Editar</a> |
	<a asp-action="Index" class="btn btn-default">Voltar</a>
</div>

WebMotors.App/Views/Anuncios/Edit.cshtml
@model WebMotors.App.Models.ViewModels.AnuncioViewModel
@{
	ViewData["Title"] = "Anuncio";
}
	<h1>Alteração de Anuncio</h1>
<hr />
<script src="~/lib/jquery/dist/jquery.js"></script>
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>			
			<div class="form-group">
				<label asp-for="Anuncio.ID" class="control-label"></label>
				<input readonly asp-for="Anuncio.ID" class="form-control" />
				<span asp-validation-for="Anuncio.ID" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Marca" class="control-label"></label>
				<select id="ddlMarca" asp-for="Anuncio.Marca" required asp-items="@(new SelectList(Model.Makes,"ID","Name"))" class="form-control">
					<option selected="selected" value="">Selecione</option>
				</select>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Modelo" class="control-label"></label>
				<select id="ddlModelo" asp-for="Anuncio.Modelo" required asp-items="@(new SelectList(string.Empty ,"ID","Name"))" class="form-control">
					<option selected="selected" value="">Selecione</option>
				</select>
				<span asp-validation-for="Anuncio.Modelo" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Versao" class="control-label"></label>
				<select id="ddlVersion" asp-for="Anuncio.Versao" required asp-items="@(new SelectList(string.Empty,"ID","Name"))" class="form-control">
					<option selected="selected" value="">Selecione</option>
				</select>
				<span asp-validation-for="Anuncio.Versao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Ano" class="control-label"></label>
				<input asp-for="Anuncio.Ano" class="form-control" />
				<span asp-validation-for="Anuncio.Ano" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Quilometragem" class="control-label"></label>
				<input asp-for="Anuncio.Quilometragem" class="form-control" />
				<span asp-validation-for="Anuncio.Quilometragem" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Anuncio.Observacao" class="control-label"></label>
				<textarea asp-for="Anuncio.Observacao" rows="5" cols="40" maxlength="200" required class="form-control"></textarea>
				<span asp-validation-for="Anuncio.Observacao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index" class="btn btn-default">Voltar</a>
</div>
<script>
	$(function () {
		$("#ddlMarca").change(function () {
			$.getJSON("/Anuncios/GetModel", { id: $("#ddlMarca").val() }, function (data) {
				var row = "";
				$("#ddlModelo").empty();
				row += "<option value=''>Selecione</option>";
				$.each(data, function (i, model) {
					row += "<option value=" + model.id + ">" + model.name + "</option>";
				});
				$("#ddlModelo").html(row);
				$("#ddlVersion").empty();
				$("#ddlVersion").html("<option value=''>Selecione</option>");
			})
		})
		$("#ddlModelo").change(function () {
			$.getJSON("/Anuncios/GetVersion", { id: $("#ddlModelo").val() }, function (data) {
				var row = "";
				$("#ddlVersion").empty();
				row += "<option value=''>Selecione</option>";
				$.each(data, function (i, version) {
					row += "<option value=" + version.id + ">" + version.name + "</option>";
				});
				$("#ddlVersion").html(row);
			})
		})
	})
</script>
@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMotors.App/Views/Anuncios/Index.cshtml
@model IEnumerable<WebMotors.App.Models.Domain.Anuncio>
@{
	ViewData["Title"] = "Anuncio";
}
	<h1>
		Anuncios
	</h1>

<p>
	<a asp-action="Create" class="btn btn-default">Criar Novo</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.ID)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Marca)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Modelo)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Versao)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Ano)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Quilometragem)
			</th>			
			<th>
				@Html.DisplayNameFor(model => model.Observacao)
			</th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.ID)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Marca)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Modelo)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Versao)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Ano)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Quilometragem)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Observacao)
			</td>
			<td>
				<a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
				<a asp-action="Details" asp-route-id="@item.ID">Detalhe</a> |
				<a asp-action="Delete" asp-route-id="@item.ID">Apagar</a>
			</td>
		</tr>
		}
	</tbody>
</table>

WebMotors.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>WebMotors -- @ViewData["Title"]</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="all,follow">
	<!-- Bootstrap CSS-->
	<link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<!-- Font Awesome CSS-->
	<link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.min.css">
	<!-- theme stylesheet-->
	<link rel="stylesheet" href="~/css/style.default.css" id="theme-stylesheet">
	<link href="~/css/style.red.css" rel="stylesheet" />
	<!-- Tweaks for older IEs-->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
	<!-- Side Navbar -->
	<nav class="side-navbar">
		<div class="side-navbar-wrapper">
			<!-- Sidebar Header    -->
			<div class="sidenav-header d-flex align-items-center justify-content-center">
				<!-- User Info-->
				<div class="sidenav-header-inner text-center">
					<div class="brand-text d-none d-md-inline-block"> <strong class="text-primary">WebMotors</strong></div>
				</div>
			</div>
			<!-- Sidebar Navigation Menus-->
			<div class="main-menu">
				<h5 class="sidenav-heading">Main</h5>
				<ul id="side-main-menu" class="side-menu list-unstyled">
					<li><a asp-area="" asp-controller="Anuncios" asp-action="Index"> <i></i>Anuncios</a></li>							
				</ul>
			</div>
		</div>
	</nav>
	<div class="page">
		<!-- navbar-->
		<header class="header">
			<nav class="navbar">
				<div class="container-fluid">
					<div class="navbar-holder d-flex align-items-center justify-content-between">
						<div class="navbar-header">
							
						</div>
						<ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
							
						</ul>
					</div>
				</div>
			</nav>
		</header>
		<!-- Breadcrumb-->
		<div class="breadcrumb-holder">
			<div class="container-fluid">
				<ul class="breadcrumb">
					<li class="breadcrumb-item"><a asp-area="" asp-controller="Anuncios" asp-action="Index">	Anuncios</a></li>
				</ul>
			</div>
		</div>
		<section>
			<div class="container-fluid">						
				<main role="main" class="pb-3">
					@RenderBody()
				</main>
			</div>
		</section>
		<footer class="main-footer">
			<div class="container-fluid">
				<div class="row">
					<div class="col-sm-6">
						<p></p>
					</div>					
				</div>
			</div>
		</footer>
	</div>
	<!-- JavaScript files-->
	<script src="~/vendor/jquery/jquery.min.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
	<script src="~/vendor/jquery.cookie/jquery.cookie.js"></script>
	<script src="~/vendor/chart.js/Chart.min.js"></script>
	<script src="~/vendor/jquery-validation/jquery.validate.min.js"></script>
	<script src="~/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
	<!-- Main File-->
	<script src="js/front.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>